add_lunch_combo demented_grouper-userdebug
add_lunch_combo demented_jflteatt-userdebug
add_lunch_combo demented_jfltetmo-userdebug
add_lunch_combo demented_jfltevzw-userdebug
add_lunch_combo demented_maguro-userdebug
add_lunch_combo demented_mako-userdebug
add_lunch_combo demented_toro-userdebug

