add_lunch_combo Droid_Concepts_grouper-userdebug
add_lunch_combo Droid_Concepts_jflteatt-userdebug
add_lunch_combo Droid_Concepts_jfltetmo-userdebug
add_lunch_combo Droid_Concepts_jfltevzw-userdebug
add_lunch_combo Droid_Concepts_maguro-userdebug
add_lunch_combo Droid_Concepts_mako-userdebug
add_lunch_combo Droid_Concepts_toro-userdebug

