#!/system/bin/sh
export PATH=/system/bin:$PATH

#run original script
##mot_boot_mode.bin

## automatic move /dalvik-cache for free space
## @bijitwit

# set perm
chmod 771 /cache 


# remove old symlink, if exist
rm /data/dalvik-cache

# move it, nothing moved if applied
cp -a /data/dalvik-cache /cache
rm -r /data/dalvik-cache

# if /cache wiped need to cr8 dir
mkdir /cache/dalvik-cache
chown system.system /cache/dalvik-cache
chmod 771 /cache/dalvik-cache

# now link
ln -s /cache/dalvik-cache /data/dalvik-cache

#
log -p w dalvik-cache is now on /cache


